import type {
  GHRepository,
  GHPullRequest,
  GHReview,
  GHCommit,
  GHUser,
} from './githubService.js';

// GitHub API shapes stop here: everything below returns RepoPulse row shapes.

/** GitHub user id → RepoPulse contributor id, for one repository */
export type ContributorIdMap = Map<number, string>;

// GitHub shows deleted accounts as "ghost"
const GHOST_LOGIN = 'ghost';

// ---- Normalized insert shapes (no id / bookkeeping columns) ----

export interface NormalizedRepository {
  github_id: number;
  name: string;
  full_name: string;
  owner: string;
  description: string | null;
  visibility: 'public' | 'private' | 'internal';
  default_branch: string;
  language: string | null;
  html_url: string | null;
  is_fork: boolean;
  is_archived: boolean;
  stargazers_count: number;
  forks_count: number;
  open_issues_count: number;
}

export interface NormalizedContributorIdentity {
  github_id: number;
  repository_id: string;
  login: string;
  avatar_url: string | null;
}

export interface NormalizedPullRequest {
  github_id: number;
  repository_id: string;
  contributor_id: string | null;
  number: number;
  title: string;
  body: string | null;
  author_login: string;
  status: 'open' | 'closed' | 'merged';
  labels: string[];
  additions: number;
  deletions: number;
  changed_files: number;
  review_count: number;
  first_review_at: string | null;
  // GitHub timestamps. cycle_time / first_review_time / pr_size are generated by Postgres.
  created_at: string;
  updated_at: string;
  merged_at: string | null;
  closed_at: string | null;
}

export type ReviewState = 'approved' | 'changes_requested' | 'commented' | 'dismissed' | 'pending';

export interface NormalizedReview {
  github_id: number;
  pull_request_id: string;
  repository_id: string;
  contributor_id: string | null;
  reviewer_login: string;
  state: ReviewState;
  submitted_at: string | null; // null for pending reviews
}

export interface NormalizedCommit {
  sha: string;
  repository_id: string;
  contributor_id: string | null;
  author_login: string | null;
  message: string;
  additions: number | null; // null until the commit's details are fetched
  deletions: number | null;
  is_merge: boolean;
  committed_at: string;
}

export interface ReviewSummary {
  reviewCount: number;
  firstReviewAt: string | null;
}

const REVIEW_STATES: ReadonlySet<string> = new Set([
  'approved',
  'changes_requested',
  'commented',
  'dismissed',
  'pending',
]);

// ---- Normalizer functions ----

export function normalizeRepository(gh: GHRepository): NormalizedRepository {
  const visibility =
    gh.visibility === 'internal' ? 'internal' : gh.private ? 'private' : 'public';
  return {
    github_id: gh.id,
    name: gh.name,
    full_name: gh.full_name,
    owner: gh.owner.login,
    description: gh.description,
    visibility,
    default_branch: gh.default_branch,
    language: gh.language,
    html_url: gh.html_url ?? null,
    is_fork: gh.fork ?? false,
    is_archived: gh.archived ?? false,
    stargazers_count: gh.stargazers_count,
    forks_count: gh.forks_count,
    open_issues_count: gh.open_issues_count,
  };
}

export function normalizeContributorIdentity(
  user: GHUser,
  repositoryId: string,
): NormalizedContributorIdentity {
  return {
    github_id: user.id,
    repository_id: repositoryId,
    login: user.login,
    avatar_url: user.avatar_url ?? null,
  };
}

export function reviewState(gh: GHReview): ReviewState | null {
  const state = gh.state.toLowerCase();
  return REVIEW_STATES.has(state) ? (state as ReviewState) : null;
}

/**
 * A PR counts as reviewed by submitted reviews from anyone other than its author
 * (self-review comments don't count). Pending reviews have no submitted_at and are
 * excluded. Dismissed reviews were submitted, so they count.
 */
export function summarizeReviews(reviews: GHReview[], authorGithubId: number | null): ReviewSummary {
  const submitted = reviews.filter(
    (r) =>
      r.submitted_at &&
      reviewState(r) !== null &&
      reviewState(r) !== 'pending' &&
      (authorGithubId === null || r.user?.id !== authorGithubId),
  );
  const first = submitted
    .map((r) => r.submitted_at as string)
    .sort((a, b) => Date.parse(a) - Date.parse(b))[0];
  return { reviewCount: submitted.length, firstReviewAt: first ?? null };
}

export function normalizePullRequest(
  gh: GHPullRequest,
  repositoryId: string,
  contributorIds: ContributorIdMap,
  reviews: ReviewSummary,
): NormalizedPullRequest {
  const status: NormalizedPullRequest['status'] =
    gh.merged_at ? 'merged' : gh.state === 'closed' ? 'closed' : 'open';

  return {
    github_id: gh.id,
    repository_id: repositoryId,
    contributor_id: gh.user ? (contributorIds.get(gh.user.id) ?? null) : null,
    number: gh.number,
    title: gh.title,
    body: gh.body,
    author_login: gh.user?.login ?? GHOST_LOGIN,
    status,
    labels: gh.labels.map((l) => l.name).filter((n): n is string => !!n),
    additions: gh.additions,
    deletions: gh.deletions,
    changed_files: gh.changed_files,
    review_count: reviews.reviewCount,
    first_review_at: reviews.firstReviewAt,
    created_at: gh.created_at,
    updated_at: gh.updated_at,
    merged_at: gh.merged_at,
    closed_at: gh.closed_at,
  };
}

/** Returns null for review states RepoPulse doesn't recognise (skipped, never guessed). */
export function normalizeReview(
  gh: GHReview,
  pullRequestId: string,
  repositoryId: string,
  contributorIds: ContributorIdMap,
): NormalizedReview | null {
  const state = reviewState(gh);
  if (!state) return null;
  return {
    github_id: gh.id,
    pull_request_id: pullRequestId,
    repository_id: repositoryId,
    contributor_id: gh.user ? (contributorIds.get(gh.user.id) ?? null) : null,
    reviewer_login: gh.user?.login ?? GHOST_LOGIN,
    state,
    submitted_at: gh.submitted_at ?? null,
  };
}

export function normalizeCommit(
  gh: GHCommit,
  repositoryId: string,
  contributorIds: ContributorIdMap,
): NormalizedCommit {
  const committedAt = gh.commit.author?.date ?? gh.commit.committer?.date;
  if (!committedAt) throw new Error(`Commit ${gh.sha} has no author or committer date`);
  const hasStats = gh.stats?.additions !== undefined && gh.stats?.deletions !== undefined;
  return {
    sha: gh.sha,
    repository_id: repositoryId,
    contributor_id: gh.author ? (contributorIds.get(gh.author.id) ?? null) : null,
    author_login: gh.author?.login ?? null,
    message: gh.commit.message.split('\n')[0].slice(0, 500),
    additions: hasStats ? (gh.stats?.additions as number) : null,
    deletions: hasStats ? (gh.stats?.deletions as number) : null,
    is_merge: gh.parents.length > 1,
    committed_at: committedAt,
  };
}
