import { describe, it, expect } from 'vitest';
import {
  normalizeCommit,
  normalizePullRequest,
  normalizeReview,
  summarizeReviews,
} from '../src/services/github/normalizer.js';
import type { GHCommit, GHPullRequest, GHReview } from '../src/services/github/githubService.js';
import { mapWithConcurrency } from '../src/utils/batch.js';

const AUTHOR = { id: 1, login: 'author' };
const REVIEWER = { id: 2, login: 'reviewer' };
const OTHER = { id: 3, login: 'other' };

function review(id: number, user: GHReview['user'], state: string, submitted_at: string | null): GHReview {
  return { id, user, state, submitted_at };
}

describe('summarizeReviews', () => {
  it('uses the earliest submitted review from someone other than the author', () => {
    const s = summarizeReviews(
      [
        review(1, AUTHOR, 'COMMENTED', '2026-09-01T09:00:00Z'), // self-review: ignored
        review(2, OTHER, 'APPROVED', '2026-09-01T15:00:00Z'),
        review(3, REVIEWER, 'CHANGES_REQUESTED', '2026-09-01T11:00:00Z'),
      ],
      AUTHOR.id,
    );
    expect(s).toEqual({ reviewCount: 2, firstReviewAt: '2026-09-01T11:00:00Z' });
  });

  it('ignores pending reviews and unknown states', () => {
    const s = summarizeReviews(
      [review(1, REVIEWER, 'PENDING', null), review(2, REVIEWER, 'SOMETHING_NEW', '2026-09-01T10:00:00Z')],
      AUTHOR.id,
    );
    expect(s).toEqual({ reviewCount: 0, firstReviewAt: null });
  });

  it('counts dismissed reviews (they were submitted)', () => {
    expect(summarizeReviews([review(1, REVIEWER, 'DISMISSED', '2026-09-02T00:00:00Z')], AUTHOR.id).reviewCount).toBe(1);
  });

  it('counts all reviewers when the author is a deleted account', () => {
    expect(summarizeReviews([review(1, REVIEWER, 'APPROVED', '2026-09-02T00:00:00Z')], null).reviewCount).toBe(1);
  });
});

describe('normalizePullRequest', () => {
  const pr: GHPullRequest = {
    id: 900,
    number: 7,
    title: 'Add cache',
    body: null,
    user: AUTHOR,
    state: 'closed',
    labels: [{ name: 'perf' }, {}],
    additions: 10,
    deletions: 4,
    changed_files: 2,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-03T00:00:00Z',
    merged_at: '2026-09-02T00:00:00Z',
    closed_at: '2026-09-02T00:00:00Z',
  };

  it('keeps GitHub timestamps, derives status, maps the author by GitHub id', () => {
    const row = normalizePullRequest(pr, 'repo', new Map([[AUTHOR.id, 'contrib-1']]), {
      reviewCount: 2,
      firstReviewAt: '2026-09-01T05:00:00Z',
    });
    expect(row).toMatchObject({
      status: 'merged',
      contributor_id: 'contrib-1',
      created_at: '2026-09-01T00:00:00Z',
      updated_at: '2026-09-03T00:00:00Z',
      labels: ['perf'],
      review_count: 2,
      first_review_at: '2026-09-01T05:00:00Z',
    });
    expect(row).not.toHaveProperty('cycle_time'); // generated by Postgres
  });

  it('records deleted authors as ghost', () => {
    const row = normalizePullRequest({ ...pr, user: null, merged_at: null }, 'repo', new Map(), {
      reviewCount: 0,
      firstReviewAt: null,
    });
    expect(row.author_login).toBe('ghost');
    expect(row.status).toBe('closed');
  });
});

describe('normalizeReview', () => {
  it('returns null for unknown states instead of guessing', () => {
    expect(normalizeReview(review(1, REVIEWER, 'BRAND_NEW', 'x'), 'pr', 'repo', new Map())).toBeNull();
  });

  it('keeps pending reviews with a null submitted_at', () => {
    expect(normalizeReview(review(1, REVIEWER, 'PENDING', null), 'pr', 'repo', new Map())).toMatchObject({
      state: 'pending',
      submitted_at: null,
    });
  });
});

describe('normalizeCommit', () => {
  const base: GHCommit = {
    sha: 'abc',
    author: null,
    commit: { author: { date: '2026-09-01T00:00:00Z' }, committer: null, message: 'Subject\n\nBody' },
    parents: [{ sha: 'p1' }],
  };

  it('leaves stats unknown when the list endpoint omits them', () => {
    expect(normalizeCommit(base, 'repo', new Map())).toMatchObject({
      additions: null,
      deletions: null,
      is_merge: false,
      message: 'Subject',
      author_login: null,
      contributor_id: null,
    });
  });

  it('flags merge commits and keeps real stats', () => {
    const row = normalizeCommit(
      { ...base, parents: [{ sha: 'p1' }, { sha: 'p2' }], stats: { additions: 0, deletions: 0 } },
      'repo',
      new Map(),
    );
    expect(row).toMatchObject({ is_merge: true, additions: 0, deletions: 0 });
  });

  it('refuses to invent a commit date', () => {
    expect(() =>
      normalizeCommit({ ...base, commit: { author: null, committer: null, message: 'm' } }, 'repo', new Map()),
    ).toThrow(/no author or committer date/);
  });
});

describe('mapWithConcurrency', () => {
  it('preserves order and never exceeds the limit', async () => {
    let active = 0;
    let peak = 0;
    const out = await mapWithConcurrency([5, 1, 4, 2, 3], 2, async (n) => {
      peak = Math.max(peak, ++active);
      await new Promise((r) => setTimeout(r, n));
      active--;
      return n * 10;
    });
    expect(out).toEqual([50, 10, 40, 20, 30]);
    expect(peak).toBe(2);
  });
});
