// ============================================================
// API contract types live in /shared/contracts.d.ts (shared with
// the backend) and are re-exported here.
// ============================================================

export type {
  ApiSuccess,
  ApiError,
  ApiResponse,
  Paginated,
  SyncStatus,
  Repository,
  PullRequestStatus,
  PullRequest,
  PullRequestSort,
  PullRequestListQuery,
  PullRequestDetail,
  WebhookEventSummary,
  ReviewState,
  Review,
  ContributorActivity,
  ContributorActivityReport,
  TimePeriod,
  AnalyticsPeriod,
  PeriodMetrics,
  ComparableMetric,
  MetricChanges,
  DataQuality,
  MetricsSummary,
  DailyTrend,
  Analytics,
  AIInsightRequest,
  AIInsight,
  AIInsightResponse,
  AIInsightMode,
  AIInsightResult,
  SessionUser,
  UserRole,
  AdminOverview,
  AdminUser,
  AdminUserUpdate,
  InstallationSummary,
  SessionInfo,
  DiscoveryResult,
} from '@shared/contracts';
